# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: weltn24/up-docker-node-chrome-headless

all_tests:
  script:
    - npm install
    - npm test

pages:
  stage: deploy
  script:
    - npm i -g typescript
    - npm i -g typedoc
    - npm run doc
    - mkdir .public
    - cp -r doc/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
